# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: secureinfra

before:
  hooks:
    - go mod tidy

builds:
  - id: bluectl
    main: ./cmd/bluectl
    binary: bluectl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/gobeyondidentity/cobalt/internal/version.Version={{.Version}}

  - id: km
    main: ./cmd/keymaker
    binary: km
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/gobeyondidentity/cobalt/internal/version.Version={{.Version}}

  - id: host-agent
    main: ./cmd/sentry
    binary: sentry
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/gobeyondidentity/cobalt/internal/version.Version={{.Version}}

  - id: control-plane
    main: ./cmd/nexus
    binary: nexus
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/gobeyondidentity/cobalt/internal/version.Version={{.Version}}

  - id: dpuemu
    main: ./dpuemu/cmd/dpuemu
    binary: dpuemu
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/gobeyondidentity/cobalt/internal/version.Version={{.Version}}

archives:
  - id: bluectl-archive
    ids:
      - bluectl
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "bluectl_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

  - id: km-archive
    ids:
      - km
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "km_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

  - id: host-agent-archive
    ids:
      - host-agent
    formats:
      - tar.gz
    name_template: "sentry_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

  - id: control-plane-archive
    ids:
      - control-plane
    formats:
      - tar.gz
    name_template: "nexus_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

  - id: dpuemu-archive
    ids:
      - dpuemu
    formats:
      - tar.gz
    name_template: "dpuemu_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-snapshot"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - name: bluectl
    ids:
      - bluectl-archive
    repository:
      owner: gobeyondidentity
      name: homebrew-cobalt
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/gobeyondidentity/cobalt"
    description: "CLI for managing BlueField DPUs via Project Cobalt"
    license: "Apache-2.0"
    install: |
      bin.install "bluectl"
    test: |
      system "#{bin}/bluectl", "--help"

  - name: km
    ids:
      - km-archive
    repository:
      owner: gobeyondidentity
      name: homebrew-cobalt
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/gobeyondidentity/cobalt"
    description: "Key management CLI for Project Cobalt"
    license: "Apache-2.0"
    install: |
      bin.install "km"
    test: |
      system "#{bin}/km", "--help"

  - name: sentry
    ids:
      - host-agent-archive
    repository:
      owner: gobeyondidentity
      name: homebrew-cobalt
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/gobeyondidentity/cobalt"
    description: "Sentry host agent for Project Cobalt attestation"
    license: "Apache-2.0"
    install: |
      bin.install "sentry"
    test: |
      system "#{bin}/sentry", "--help"

  - name: nexus
    ids:
      - control-plane-archive
    repository:
      owner: gobeyondidentity
      name: homebrew-cobalt
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/gobeyondidentity/cobalt"
    description: "Nexus control plane for Project Cobalt"
    license: "Apache-2.0"
    install: |
      bin.install "nexus"
    test: |
      system "#{bin}/nexus", "--help"

  - name: dpuemu
    ids:
      - dpuemu-archive
    repository:
      owner: gobeyondidentity
      name: homebrew-cobalt
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/gobeyondidentity/cobalt"
    description: "DPU emulator for Project Cobalt local development"
    license: "Apache-2.0"
    install: |
      bin.install "dpuemu"
    test: |
      system "#{bin}/dpuemu", "--help"

nfpms:
  # CLI tools (no systemd, just binaries)
  - id: bluectl-pkg
    package_name: bluectl
    ids:
      - bluectl
    vendor: Beyond Identity
    homepage: https://github.com/gobeyondidentity/cobalt
    maintainer: Beyond Identity <support@beyondidentity.com>
    description: CLI for managing BlueField DPUs via Project Cobalt
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    priority: optional

  - id: km-pkg
    package_name: km
    ids:
      - km
    vendor: Beyond Identity
    homepage: https://github.com/gobeyondidentity/cobalt
    maintainer: Beyond Identity <support@beyondidentity.com>
    description: Key management CLI for Project Cobalt
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    priority: optional

  # Services (with systemd, config, and scripts)
  - id: host-agent-pkg
    package_name: sentry
    ids:
      - host-agent
    vendor: Beyond Identity
    homepage: https://github.com/gobeyondidentity/cobalt
    maintainer: Beyond Identity <support@beyondidentity.com>
    description: Sentry - Project Cobalt host agent for attestation and posture collection
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: admin
    priority: optional
    contents:
      - src: packaging/systemd/sentry.service
        dst: /lib/systemd/system/sentry.service
        type: config
      - src: packaging/config/sentry.yaml
        dst: /etc/secureinfra/sentry.yaml
        type: config|noreplace
    scripts:
      postinstall: packaging/scripts/postinstall.sh
      preremove: packaging/scripts/preremove.sh
    overrides:
      rpm:
        dependencies:
          - systemd
      deb:
        dependencies:
          - systemd

  - id: control-plane-pkg
    package_name: nexus
    ids:
      - control-plane
    vendor: Beyond Identity
    homepage: https://github.com/gobeyondidentity/cobalt
    maintainer: Beyond Identity <support@beyondidentity.com>
    description: Nexus - Project Cobalt control plane for policy enforcement and attestation verification
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: admin
    priority: optional
    contents:
      - src: packaging/systemd/nexus.service
        dst: /lib/systemd/system/nexus.service
        type: config
      - src: packaging/config/nexus.yaml
        dst: /etc/secureinfra/nexus.yaml
        type: config|noreplace
    scripts:
      postinstall: packaging/scripts/postinstall.sh
      preremove: packaging/scripts/preremove.sh
    overrides:
      rpm:
        dependencies:
          - systemd
      deb:
        dependencies:
          - systemd

release:
  github:
    owner: gobeyondidentity
    name: cobalt
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
